# Generated by Django 3.1.7 on 2021-04-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.CharField(default=5, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
