# Generated by Django 3.1.7 on 2021-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
