# Generated by Django 3.1.7 on 2021-04-19 01:43

from django.db import migrations


def populate_db(appreg, ed):
    lb = appreg.get_model('unitconvert', 'lb')
    me = lb()
    me.save()

    Ounces = appreg.get_model('unitconvert', 'Ounces')
    me2 = Ounces()
    me2.save()

    t_oz = appreg.get_model('unitconvert', 't_oz')
    me3 = t_oz()
    me3.save()

    kg = appreg.get_model('unitconvert', 'kg')
    me4 = kg()
    me4.save()

    g = appreg.get_model('unitconvert', 'g')
    me5 = g()
    me5.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unitconvert', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
