/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CS3100_Assign4;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static final Runtime runTime = Runtime.getRuntime();
    private static final ArrayList<WorkerThread> workerThreads = new ArrayList<>();

    public static void main(String[] args) throws InterruptedException {
        int[] digits = new int[1000];
        for (int i = 0; i < digits.length; i++) {
            digits[i] = i + 1;
        }

        TaskQueue myQueue = new TaskQueue(digits);
        MyTable hashTable = new MyTable();

        System.out.print("\nStarting Calculations...");
        Thread.sleep(2000);
        hashTable.startClock();

        for (int i = 0; i < runTime.availableProcessors(); i++) {
            WorkerThread thread = new WorkerThread(myQueue, hashTable);

            workerThreads.add(thread);
            thread.start();
        }

        for (Thread thread : workerThreads) {
            thread.join();
        }

        hashTable.printPi();
    }
}
